apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
        - name: fastapi
          image: us-central1-docker.pkg.dev/fleetproject-403015/blog/backend:latest
          ports:
            - containerPort: 8080
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          args:
            - "--auto-iam-authn"
            - "--port=5432"
            - "fleetproject-403015:us-central1:blog-db"
          securityContext:
            runAsNonRoot: true
            
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
